### ISSUE TITLE
Clarification on your question 

### ISSUE THREAD

**Issue by shrikanthkr** [RealImage/challenge2019#2]
I have been reading through the question based on the sample input and output mentioned in the README.

Theatre | Size Slab (in GB) | Minimum cost | Cost Per GB | Partner ID
-- | -- | -- | -- | --
T1 | 0-200 | 2000 | 20 | P1
T1 | 200-400 | 3000 | 15 | P1
T3 | 100-200 | 4000 | 30 | P1
T3 | 200-400 | 5000 | 25 | P1
T5 | 100-200 | 2000 | 30 | P1
T1 | 0-400 | 1500 | 25 | P2

---

> Problem 1, Input 2

Am unsure how the output is achieved as **D2, true, P1, 4500**

Based on my understanding

300 is split into two slabs. (Since output says only p1)

1. T1 | 0-200 | 2000 | 20 | P1 -> 200 goes here
2. T1 | 200-400 | 3000 | 15 | P1 -> 100 goes here.

If the above is correct then (200 * 20) + (100 * 15) = 5500

I was not able to understand how 4500 was achieved. 

Following up with the next use case, 50 gets added which makes sense from the previous value where 750 is getting added. (50 * 15) from the second slab. 

---
Questions:

1. I just want to clarify, if am missing anything over here ? 
2. The minimum costs for the second slab is not considered as its 3000. So the minimum cost is always considered from the total amount calculated for the partner itself or for the size slabs separetely ? 

Would be great if you can clarify these items, Thanks.

**Comment by maknahar** [comment]
Hi @shrikanthkr, 

Thanks for writing to us. 

>I just want to clarify, if am missing anything over here ?

> 300 is split into two slabs. (Since output says only p1)

Deliveries are not split into multiple slabs. Content size slabs are used to find out the price per GB for the whole content that needs to be delivered. So to deliver 300 GB via P1 it falls into 200-400 slab which has the price per GB as 15. 15*300 = 4500.

I understand why this would create confusion. I will make it explicit.

> The minimum costs for the second slab is not considered as its 3000. So the minimum cost is always considered from the total amount calculated for the partner itself or for the size slabs separetely ?

Minimum cost is the price that will be charged at minimum irrespective of content size. i.e. The minimum cost comes into play only when the total cost of delivery comes less than the minimum cost of the selected cost. In this case, 4500 > 3000 so minimum cost criteria is satisfied automatically. Hope it helps. Let me know if you need further clarification.

**Comment by shrikanthkr** [comment]
@maknahar Thanks for the clarification. The term slab actually meant to me like, I can split the total content across slabs. This was helpful.
Maybe the term range might help in place slabs.  

Thanks again for clarifying the second part.
